import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
//components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AuthProvider from "@/app/_providers/auth";
import { UserFavoriteExerciseProvider } from "./_context/favoriteExercisesContext";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-oswald",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-primary-300">
      <body
        className={`${oswald.variable} ${roboto.variable} w-full max-w-[1920px] min-h-full mx-auto bg-white`}
      >
        <AuthProvider>
          <UserFavoriteExerciseProvider>
            {children}
          </UserFavoriteExerciseProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
